ideas_portal_categories:
  type: list
  list_type: category
  default: ""
  description: "Select categories where the Ideas Portal styling should be applied."

  ideas_portal_tags:
  type: list
  list_type: tag
  default: ""
  description: "Select tags where the Ideas Portal styling should be applied."